version: '3.8'

services:
  janus:
    build:
      context: ./janus
      dockerfile: Dockerfile
    container_name: janus
    ports:
      - "8088:8088"
      - "8089:8089"
      - "8188:8188"
      - "8189:8189"
      - "10001-10200:10001-10200/udp"
    networks:
      - webrtc_network

  gstreamer:
    build:
      context: ./gstreamer
      dockerfile: Dockerfile
    container_name: gstreamer
    devices:
      - "/dev/video0:/dev/video0"
    depends_on:
      - janus
    ports:
      - '10000:10000/udp'
    networks:
      - webrtc_network

networks:
  webrtc_network:
    driver: bridge
