import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from './StoreProvider';
import Navigation from '@/components/Navigation';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="bg-gray-950 text-gray-100">
                <StoreProvider>
                    <Navigation />
                    <div className="pt-16">{children}</div>
                </StoreProvider>
            </body>
        </html>
    );
}
