import type { Metadata } from 'next';

// import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/layout/Navigation';
import { WebSocketProvider } from '@/context/WebSocketContext';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-950 text-gray-100 h-screen overflow-hidden">
        <WebSocketProvider>
          <Navigation />
          <div className="mt-16 h-full overflow-auto">{children}</div>
        </WebSocketProvider>
      </body>
    </html>
  );
}
