version: "3.5"
services:
  mysql:
    image: mysql:8.3.0
    container_name: embr-db
    environment:
      MYSQL_DATABASE: 'embr'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'pw'
      MYSQL_ROOT_PASSWORD: 'rpw'
    ports:
      - '3307:3306'       # Exposing on port 3307 to avoid conflicts with other MySQL instances on my machine
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
      - ./docker/ddl:/docker-entrypoint-initdb.d  # Automatically loads SQL setup on first run
